// Generated by CoffeeScript 1.3.1
(function() {
  var db, end, mongo, news, where;

  mongo = require('mongoskin');

  db = mongo.db('localhost:27017/zxg');

  news = db.collection('news');

  (function(data) {
    if (data == null) {
      data = 2;
    }
    return console.log('data', data);
  });

  [1, 2, 3, 4, 5].map(function(i) {
    var row;
    row = {
      title: "title" + i,
      content: "content" + i,
      created_at: new Date(),
      updated_at: new Date(),
      addtime: funs.get_unix_timestamp()
    };
    return news.insert(row);
  });

  'start = new Date(2012,5,1)\nend = new Date(2012,6,1)\nwhere =  "created_at": "$gte": start, "$lt": end\n\nnews.find(where).toArray (err, items) ->\n	console.log \'items range\',items';


  end = funs.get_date_from_unix_timestamp(1338532555);

  where = {
    "created_at": {
      $lte: end
    }
  };

  console.log('where', where);

  news.find(where).toArray(function(err, items) {
    console.log('items lte', items);
    return console.log(JSON.stringify(items));
  });

  'test_date.find().toArray (err, items) ->\n	items.map ( item ) ->\n		data_id = item[\'_id\']\n		timestamp = data_id.toString().substring(0,8)\n		date = new Date( parseInt( timestamp, 16 ) * 1000 )\n		\n		console.log \'timestamp\',timestamp,\'date\',date,\'item\',item\n		\n		current_timestamp = Date.parse(new Date());\n		console.log \'current_timestamp\',current_timestamp';


}).call(this);
